name: Deploy to Azure INFRA

on: 
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main
      
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          version: 1.7.5
          

      - name: Verify TerraformVersion
        run: terraform -version

        
          
            
      
