name: Deploy to Azure INFRA

on: 
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

permissions: 
 contents: read
 id-token: write
 
jobs:
  TerraformInstall:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          
      - name: Verify TerraformVersion
        run: terraform -version

      - name: terraformInit
        run: terraform init
        working-directory: env/dev/

      - name: terraformPlan
        run: terraform plan
        working-directory: env/dev/

   
  
 
  
        
          
            
      
