name: INFARPRovsioned
on: 
  push:
    branches: 
      - main
      - release/*

  pull_request:
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: 
      labels: self-hosted, Linux, X64

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
        version: 1.7.5
    - name: Verify TerraformVersion
      uses: dflook/terraform-version@v1.29.1
      
        
          
    
