name: INFARPRovsioned
on: 
  push:
    branches: 
      - main
      - release/*

  pull_request:
    branches: 
      - main
jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        version: 1.7.5
    - name: Verify TerraformVersion
      uses: dflook/terraform-version@v1.29.1
      
        
          
    
