name: Terraform Azure

on:
  push:
    branches:
      - main   # sirf main branch pe push hone par chalega
  pull_request:
    branches:
      - main   # PR main branch pe raise hone par chalega
  workflow_dispatch:   # manually trigger karne ka option milega GitHub Actions tab pe

jobs:
  terraform:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

