# name: Terraform

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:

# permissions:
#   contents: read
#   id-token: write  # Needed for OIDC if used

# jobs:
#   terraform:
#     runs-on: [self-hosted, linux, x64]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       # Install Azure CLI (in case runner doesn’t have it already)
#       - name: Setup Azure CLI
#         run: |
#           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#           az version

#       # Login to Azure
#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Install Terraform
#         uses: little-core-labs/install-terraform@v2.0.0
#         with:
#           version: 1.7.5
          

#       - name: Terraform Init
#         run: terraform init

#       - name: Terraform Plan
#         run: terraform plan -input=false
